### model
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

### method
stage: sft
do_train: true
finetuning_type: lora
lora_target: all

### dataset
dataset: ccd_Barge.json, ccd_BulkCarrier.json, ccd_ChemicalTanker.json, ccd_ContainerShip.json, ccd_Cruise.json, ccd_Dredger.json, ccd_Ferry.json, ccd_GeneralCargoShip.json, ccd_HarbourLaunch-PilotVessel.json, ccd_LNG-LPG.json, ccd_RORO.json, ccd_Sampan.json, ccd_SupplyVessel.json, ccd_Tanker-Bunker.json, ccd_Trawler-FishingVessel.json, ccd_Tugboat.json, ccd_Yacht.json, flir_Barge.json, flir_BulkCarrier.json, flir_ContainerShip.json, flir_Cruise.json, flir_Dredger.json, flir_Ferry.json, flir_HarbourLaunch-PilotVessel.json, flir_LNG-LPG.json, flir_RORO.json, flir_Sampan.json, flir_SupplyVessel.json, flir_Tanker-Bunker.json, flir_Trawler-FishingVessel.json, flir_Tugboat.json, flir_Yacht.json, swir_Barge.json, swir_BulkCarrier.json, swir_ChemicalTanker.json, swir_ContainerShip.json, swir_Cruise.json, swir_Dredger.json, swir_Ferry.json, swir_GeneralCargoShip.json, swir_HarbourLaunch-PilotVessel.json, swir_HeavyLoad.json, swir_LNG-LPG.json, swir_RORO.json, swir_Sampan.json, swir_SupplyVessel.json, swir_Tanker-Bunker.json, swir_Trawler-FishingVessel.json, swir_Tugboat.json, swir_Yacht.json
template: qwen2_vl
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: saves/qwen2_vl-7b/lora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-4
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500
